<?php

include_once('cod_bof.features.inc');



/*function cod_bof_schedule($ajax = FALSE) {
  // COD BoF uses Prepopulate so retrieve room and time slot from the request.
  if (isset($_REQUEST['edit'])) {
    $room_nid = $_REQUEST['edit']['field_session_room']['nid']['nid'];
    $slot_nid = $_REQUEST['edit']['field_session_slot']['nid']['nid'];
    // Pass along Prepopulate and destination parameters in case the user
    // chooses to add a new BoF.
    $url_query = array(
      'edit[field_session_room][nid][nid]' => $room_nid,
      'edit[field_session_slot][nid][nid]' => $slot_nid,
    );
    $room = node_load($room_nid);
    $slot = node_load($slot_nid);
    // Sanity check that bad data wasn't passed.
    if ($slot->type != 'time_slot' || $slot->status != 1 || $room->type != 'room' || $room->status != 1) {
      drupal_access_denied();
      return;
    }
  }
  else {
    // No arguments so 404.
    drupal_not_found();
    return;
  }
  
  if (!$ajax) {
    return drupal_get_form('cod_bof_schedule_form', $room, $slot, $url_query);
  }

  $form_state = array(
    'ajax' => TRUE,
    'title' => t('Schedule'),
    'args' => array($room, $slot, $url_query),
  );
  $output = dialog_form_wrapper('cod_bof_schedule_form', $form_state);
  if (empty($output)) {
    $output[] = dialog_command_display(t('Comment submitted'), t('Reloading...'));
    $output[] = ctools_ajax_command_reload();
  }
  ctools_ajax_render($output);
}*/







